NOTEit/NOTEit/Models/Mark.cs
using System.ComponentModel.DataAnnotations;

namespace NOTEit.Models
{
    public class Mark
    {
        public int Id { get; set; }

        [Required, Range(1, 6, ErrorMessage = "Die Note muss zwischen 1 und 6 sein."), Display(Name = "Note")]
        public double Grade { get; set; }

        [Required, Display(Name = "Fach")]
        public virtual Subject Subject { get; set; }

        [Required, Display(Name = "Semester")]
        public virtual Semester Semester { get; set; }

        public virtual WishMark WishMark { get; set; }
    }
}

NOTEit/NOTEit/ViewModels/Mark/MarkFormViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace NOTEit.ViewModels.Mark
{
    public class MarkFormViewModel
    {
        public int Id { get; set; }

        [Required, Range(1, 6, ErrorMessage = "Die Note muss zwischen 1 und 6 sein."), Display(Name = "Note")]
        public double Grade { get; set; }

        [Required, Display(Name = "Fach")]
        public int Subject { get; set; }

        public virtual ICollection<Models.Subject> AllSubjects { get; set; }

        [Required, Display(Name = "Semester")]
        public int Semester { get; set; }

        public virtual ICollection<Models.Semester> AllSemesters { get; set; }
    }
}

NOTEit/NOTEit/Controllers/MarkController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using NOTEit.Models;
using NOTEit.ViewModels.Mark;

namespace NOTEit.Controllers
{
    [Authorize(Roles = "Apprentice")]
    public class MarkController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();
        private readonly string _userId = System.Web.HttpContext.Current.User.Identity.GetUserId();

        public ActionResult Index()
        {
            return View(_db.Marks.Where(x => x.Subject.Owner.Id == _userId).ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var mark = _db.Marks.Find(id);
            if (mark == null || mark.Subject.Owner.Id != _userId)
            {
                return HttpNotFound();
            }
            return View(mark);
        }

        public ActionResult Create()
        {
            return View(
                new MarkFormViewModel
                {
                    AllSemesters = _db.Semesters.Where(x => x.Subjects.Any(y => y.Owner.Id == _userId)).ToList(),
                    AllSubjects = _db.Subjects.Where(x => x.Owner.Id == _userId).ToList()
                }
            );
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MarkFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(
                    new MarkFormViewModel
                    {
                        Grade = viewModel.Grade,
                        Subject = viewModel.Subject,
                        Semester = viewModel.Semester,
                        AllSemesters = _db.Semesters.Where(x => x.Subjects.Any(y => y.Owner.Id == _userId)).ToList(),
                        AllSubjects = _db.Subjects.Where(x => x.Owner.Id == _userId).ToList()
                    }
                );

            if ((bool)!_db.Semesters.FirstOrDefault(x => x.Id == viewModel.Semester)?.Subjects.Contains(_db.Subjects.FirstOrDefault(y => y.Id == viewModel.Subject)))
            {
                ModelState.AddModelError("Subject", "Dieses Fach ist nicht im ausgewählten Semester.");
                return View(
                    new MarkFormViewModel
                    {
                        Grade = viewModel.Grade,
                        Subject = viewModel.Subject,
                        Semester = viewModel.Semester,
                        AllSemesters = _db.Semesters.Where(x => x.Subjects.Any(y => y.Owner.Id == _userId)).ToList(),
                        AllSubjects = _db.Subjects.Where(x => x.Owner.Id == _userId).ToList()
                    }
                );
            }

            var mark = new Mark
            {
                Grade = viewModel.Grade,
                Semester = _db.Semesters.Find(viewModel.Semester),
                Subject = _db.Subjects.Find(viewModel.Subject),
                WishMark = _db.WishMarks.FirstOrDefault(x => x.Semester.Id == viewModel.Semester && x.Subject.Id == viewModel.Subject)
            };

            _db.Marks.Add(mark);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var mark = _db.Marks.Find(id);
            if (mark == null || mark.Subject.Owner.Id != _userId)
            {
                return HttpNotFound();
            }
            return View(
                new MarkFormViewModel
                {
                    Id = mark.Id,
                    Grade = mark.Grade,
                    Subject = mark.Subject.Id,
                    Semester = mark.Semester.Id,
                    AllSemesters = _db.Semesters.Where(x => x.Subjects.Any(y => y.Owner.Id == _userId)).ToList(),
                    AllSubjects = _db.Subjects.Where(x => x.Owner.Id == _userId).ToList()
                }
            );
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MarkFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(
                    new MarkFormViewModel
                    {
                        Id = viewModel.Id,
                        Grade = viewModel.Grade,
                        Subject = viewModel.Subject,
                        Semester = viewModel.Semester,
                        AllSemesters = _db.Semesters.Where(x => x.Subjects.Any(y => y.Owner.Id == _userId)).ToList(),
                        AllSubjects = _db.Subjects.Where(x => x.Owner.Id == _userId).ToList()
                    }
                );

            if ((bool)!_db.Semesters.FirstOrDefault(x => x.Id == viewModel.Semester)?.Subjects.Contains(_db.Subjects.FirstOrDefault(y => y.Id == viewModel.Subject)))
            {
                ModelState.AddModelError("Subject", "Dieses Fach ist nicht im ausgewählten Semester.");
                return View(
                    new MarkFormViewModel
                    {
                        Id = viewModel.Id,
                        Grade = viewModel.Grade,
                        Subject = viewModel.Subject,
                        Semester = viewModel.Semester,
                        AllSemesters = _db.Semesters.Where(x => x.Subjects.Any(y => y.Owner.Id == _userId)).ToList(),
                        AllSubjects = _db.Subjects.Where(x => x.Owner.Id == _userId).ToList()
                    }
                );
            }

            var mark = _db.Marks.FirstOrDefault(x => x.Id == viewModel.Id);
            if (mark == null || mark.Subject.Owner.Id != _userId) return View("Error");
            mark.Grade = viewModel.Grade;
            mark.Semester = _db.Semesters.Find(viewModel.Semester);
            mark.Subject = _db.Subjects.Find(viewModel.Subject);
            mark.WishMark = _db.WishMarks.FirstOrDefault(x => x.Semester.Id == viewModel.Semester && x.Subject.Id == viewModel.Subject);

            _db.Entry(mark).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var mark = _db.Marks.Find(id);
            if (mark == null || mark.Subject.Owner.Id != _userId)
            {
                return HttpNotFound();
            }
            return View(mark);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var mark = _db.Marks.Find(id);
            if (mark == null || mark.Subject.Owner.Id != _userId) return View("Error");
            _db.Marks.Remove(mark);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NOTEit/NOTEit/Controllers/SemesterController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using NOTEit.Models;
using NOTEit.ViewModels.Semester;

namespace NOTEit.Controllers
{
    [Authorize(Roles = "Apprentice")]
    public class SemesterController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();
        private readonly string _userId = System.Web.HttpContext.Current.User.Identity.GetUserId();

        public ActionResult Index()
        {
            return View(_db.Semesters.Where(x => x.Subjects.Any(y => y.Owner.Id == _userId)).ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var semester = _db.Semesters.Find(id);
            if (semester == null || semester.Subjects.All(x => x.Owner.Id != _userId))
            {
                return HttpNotFound();
            }
            return View(semester);
        }

        public ActionResult Create()
        {
            return View(
                new SemesterFormViewModel
                {
                    AllSubjects = _db.Subjects.Where(x => x.Owner.Id == _userId).ToList()
                }
            );
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SemesterFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(
                    new SemesterFormViewModel
                    {
                        Name = viewModel.Name,
                        Subjects = viewModel.Subjects,
                        AllSubjects = _db.Subjects.Where(x => x.Owner.Id == _userId).ToList()
                    }
                );

            if (!viewModel.Subjects.Any())
            {
                ModelState.AddModelError("Subjects", "Wählen Sie mindestens ein Fach aus");
                return View(
                    new SemesterFormViewModel
                    {
                        Name = viewModel.Name,
                        Subjects = viewModel.Subjects,
                        AllSubjects = _db.Subjects.Where(x => x.Owner.Id == _userId).ToList()
                    }
                );
            }

            var semester = new Semester
            {
                Name = viewModel.Name,
                Subjects = _db.Subjects.Where(x => viewModel.Subjects.Contains(x.Id)).ToList()
            };

            _db.Semesters.Add(semester);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var semester = _db.Semesters.Find(id);
            if (semester == null || semester.Subjects.All(x => x.Owner.Id != _userId))
            {
                return HttpNotFound();
            }
            return View(
                new SemesterFormViewModel
                {
                    Id = semester.Id,
                    Name = semester.Name,
                    Subjects = semester.Subjects.Select(x => x.Id).ToList(),
                    AllSubjects = _db.Subjects.Where(x => x.Owner.Id == _userId).ToList()
                }
            );
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SemesterFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(
                    new SemesterFormViewModel
                    {
                        Name = viewModel.Name,
                        Subjects = viewModel.Subjects,
                        AllSubjects = _db.Subjects.Where(x => x.Owner.Id == _userId).ToList()
                    }
                );

            if (!viewModel.Subjects.Any())
            {
                ModelState.AddModelError("Subjects", "Wählen Sie mindestens ein Fach aus");
                return View(
                    new SemesterFormViewModel
                    {
                        Name = viewModel.Name,
                        Subjects = viewModel.Subjects,
                        AllSubjects = _db.Subjects.Where(x => x.Owner.Id == _userId).ToList()
                    }
                );
            }

            var semester = _db.Semesters.FirstOrDefault(x => x.Id == viewModel.Id);
            if (semester == null || semester.Subjects.All(x => x.Owner.Id != _userId)) return View("Error");
            semester.Name = viewModel.Name;
            semester.Subjects.Clear();
            semester.Subjects = _db.Subjects.Where(x => viewModel.Subjects.Contains(x.Id)).ToList();

            _db.Entry(semester).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var semester = _db.Semesters.Find(id);
            if (semester == null || semester.Subjects.All(x => x.Owner.Id != _userId))
            {
                return HttpNotFound();
            }
            return View(semester);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var semester = _db.Semesters.Find(id);
            if (semester == null || semester.Subjects.All(x => x.Owner.Id != _userId)) return View("Error");
            _db.Semesters.Remove(semester);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NOTEit/NOTEit/Views/Mark/Create.cshtml
@model NOTEit.ViewModels.Mark.MarkFormViewModel

@{
    ViewBag.Title = "Erstellen";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Note</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.Partial("_Form")

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Erstellen" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Zurück zur Übersicht", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {
            $("#Subject").chosen({
                placeholder_text_single: "Wählen Sie ein Fach aus",
                no_results_text: "Sie haben noch kein Fach erstellt"
            });

            $("#Semester").chosen({
                placeholder_text_single: "Wählen Sie ein Semester aus",
                no_results_text: "Sie haben noch kein Semester erstellt"
            });
        });
    </script>
}

NOTEit/NOTEit/Views/Mark/Delete.cshtml
@model NOTEit.Models.Mark

@{
    ViewBag.Title = "Löschen";
}

<h2>@ViewBag.Title</h2>

<h3>Wollen Sie diese Note wirklich löschen?</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Semester, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Semester, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.Semester, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Löschen" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Zurück zur Übersicht", "Index")
</div>

NOTEit/NOTEit/Views/Mark/Details.cshtml
@model NOTEit.Models.Mark

@{
    ViewBag.Title = "Details";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Note</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Semester, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Semester, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.Semester, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Bearbeiten", "Edit", "Mark", new { id = Model.Id }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Zurück zur Übersicht", "Index")
</div>

NOTEit/NOTEit/Views/Mark/Edit.cshtml
@model NOTEit.ViewModels.Mark.MarkFormViewModel

@{
    ViewBag.Title = "Bearbeiten";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Note</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(x => x.Id)
        @Html.Partial("_Form")

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Speichern" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Zurück zur Übersicht", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {
            $("#Subject").chosen({
                placeholder_text_single: "Wählen Sie ein Fach aus",
                no_results_text: "Sie haben noch kein Fach erstellt"
            });

            $("#Semester").chosen({
                placeholder_text_single: "Wählen Sie ein Semester aus",
                no_results_text: "Sie haben noch kein Semester erstellt"
            });
        });
    </script>
}

NOTEit/NOTEit/Views/Mark/Index.cshtml
@model IEnumerable<NOTEit.Models.Mark>

@{
    ViewBag.Title = "Notenliste";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Neue Note erstellen", "Create")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Grade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Semester)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Subject)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Grade)
            </td>
            <td>
                @Html.ActionLink(item.Semester.Name, "Edit", "Semester", new { id = item.Semester.Id }, null)
            </td>
            <td>
                @Html.ActionLink(item.Subject.Name, "Edit", "Subject", new { id = item.Subject.Id }, null)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Bearbeiten", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Löschen", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

NOTEit/NOTEit/Views/Mark/_Form.cshtml
@model NOTEit.ViewModels.Mark.MarkFormViewModel

<div class="form-group">
    @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Semester, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.DropDownListFor(model => model.Semester, new SelectList(Model.AllSemesters, "Id", "Name"), new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Semester, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.DropDownListFor(model => model.Subject, new SelectList(Model.AllSubjects, "Id", "Name"), new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
    </div>
</div>