NOTEit/NOTEit/Models/Semester.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace NOTEit.Models
{
    public class Semester
    {
        public int Id { get; set; }

        [Required, Display(Name = "Name")]
        public string Name { get; set; }

        [Required, Display(Name = "Fächer")]
        public virtual ICollection<Subject> Subjects { get; set; }

        public virtual ICollection<WishMark> WishMarks { get; set; }
    }
}

NOTEit/NOTEit/ViewModels/Semester/SemesterFormViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace NOTEit.ViewModels.Semester
{
    public class SemesterFormViewModel
    {
        public int Id { get; set; }

        [Required, Display(Name = "Name")]
        public string Name { get; set; }
        
        [Required, Display(Name = "Fächer")]
        public virtual ICollection<int> Subjects { get; set; } = new List<int>();
        
        public virtual ICollection<Models.Subject> AllSubjects { get; set; }
    }
}

NOTEit/NOTEit/Controllers/SemesterController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using NOTEit.Models;
using NOTEit.ViewModels.Semester;

namespace NOTEit.Controllers
{
    [Authorize(Roles = "Apprentice")]
    public class SemesterController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();
        private readonly string _userId = System.Web.HttpContext.Current.User.Identity.GetUserId();

        public ActionResult Index()
        {
            return View(_db.Semesters.Where(x => x.Subjects.Any(y => y.Owner.Id == _userId)).ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var semester = _db.Semesters.Find(id);
            if (semester == null || semester.Subjects.All(x => x.Owner.Id != _userId))
            {
                return HttpNotFound();
            }
            return View(semester);
        }

        public ActionResult Create()
        {
            return View(
                new SemesterFormViewModel
                {
                    AllSubjects = _db.Subjects.Where(x => x.Owner.Id == _userId).ToList()
                }
            );
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SemesterFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(
                    new SemesterFormViewModel
                    {
                        Name = viewModel.Name,
                        Subjects = viewModel.Subjects,
                        AllSubjects = _db.Subjects.Where(x => x.Owner.Id == _userId).ToList()
                    }
                );

            if (!viewModel.Subjects.Any())
            {
                ModelState.AddModelError("Subjects", "Wählen Sie mindestens ein Fach aus");
                return View(
                    new SemesterFormViewModel
                    {
                        Name = viewModel.Name,
                        Subjects = viewModel.Subjects,
                        AllSubjects = _db.Subjects.Where(x => x.Owner.Id == _userId).ToList()
                    }
                );
            }

            var semester = new Semester
            {
                Name = viewModel.Name,
                Subjects = _db.Subjects.Where(x => viewModel.Subjects.Contains(x.Id)).ToList()
            };

            _db.Semesters.Add(semester);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var semester = _db.Semesters.Find(id);
            if (semester == null || semester.Subjects.All(x => x.Owner.Id != _userId))
            {
                return HttpNotFound();
            }
            return View(
                new SemesterFormViewModel
                {
                    Id = semester.Id,
                    Name = semester.Name,
                    Subjects = semester.Subjects.Select(x => x.Id).ToList(),
                    AllSubjects = _db.Subjects.Where(x => x.Owner.Id == _userId).ToList()
                }
            );
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SemesterFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(
                    new SemesterFormViewModel
                    {
                        Name = viewModel.Name,
                        Subjects = viewModel.Subjects,
                        AllSubjects = _db.Subjects.Where(x => x.Owner.Id == _userId).ToList()
                    }
                );

            if (!viewModel.Subjects.Any())
            {
                ModelState.AddModelError("Subjects", "Wählen Sie mindestens ein Fach aus");
                return View(
                    new SemesterFormViewModel
                    {
                        Name = viewModel.Name,
                        Subjects = viewModel.Subjects,
                        AllSubjects = _db.Subjects.Where(x => x.Owner.Id == _userId).ToList()
                    }
                );
            }

            var semester = _db.Semesters.FirstOrDefault(x => x.Id == viewModel.Id);
            if (semester == null || semester.Subjects.All(x => x.Owner.Id != _userId)) return View("Error");
            semester.Name = viewModel.Name;
            semester.Subjects.Clear();
            semester.Subjects = _db.Subjects.Where(x => viewModel.Subjects.Contains(x.Id)).ToList();

            _db.Entry(semester).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var semester = _db.Semesters.Find(id);
            if (semester == null || semester.Subjects.All(x => x.Owner.Id != _userId))
            {
                return HttpNotFound();
            }
            return View(semester);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var semester = _db.Semesters.Find(id);
            if (semester == null || semester.Subjects.All(x => x.Owner.Id != _userId)) return View("Error");
            _db.Semesters.Remove(semester);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NOTEit/NOTEit/Controllers/SubjectController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using NOTEit.Models;
using NOTEit.ViewModels.Subject;

namespace NOTEit.Controllers
{
    [Authorize(Roles = "Apprentice")]
    public class SubjectController : Controller
    {
        private readonly ApplicationDbContext _db = new ApplicationDbContext();
        private readonly string _userId = System.Web.HttpContext.Current.User.Identity.GetUserId();

        public ActionResult Index()
        {
            return View(_db.Subjects.Where(x => x.Owner.Id == _userId).ToList());
        }
        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var subject = _db.Subjects.Find(id);
            if (subject == null || subject.Owner.Id != _userId)
            {
                return HttpNotFound();
            }
            return View(subject);
        }
        
        public ActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SubjectFormViewModel viewModel)
        {
            if (!ModelState.IsValid) return View(viewModel);

            var subject = new Subject
            {
                Name = viewModel.Name,
                Owner = _db.Users.Find(_userId)
            };

            _db.Subjects.Add(subject);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }
        
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var subject = _db.Subjects.Find(id);
            if (subject == null || subject.Owner.Id != _userId)
            {
                return HttpNotFound();
            }
            return View(
                new SubjectFormViewModel
                {
                    Id = subject.Id,
                    Name = subject.Name
                }
            );
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SubjectFormViewModel viewModel)
        {
            if (!ModelState.IsValid) return View(viewModel);

            var subject = _db.Subjects.FirstOrDefault(x => x.Id == viewModel.Id);
            if (subject == null || subject.Owner.Id != _userId) return View("Error");
            subject.Name = viewModel.Name;

            _db.Entry(subject).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var subject = _db.Subjects.Find(id);
            if (subject == null || subject.Owner.Id != _userId)
            {
                return HttpNotFound();
            }
            return View(subject);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var subject = _db.Subjects.Find(id);
            if (subject == null || subject.Owner.Id != _userId) return View("Error");
            _db.Subjects.Remove(subject);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NOTEit/NOTEit/Views/Semester/Create.cshtml
@model NOTEit.ViewModels.Semester.SemesterFormViewModel

@{
    ViewBag.Title = "Erstellen";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Semester</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.Partial("_Form")

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Erstellen" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Zurück zur Übersicht", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {
            $("#Subjects").chosen({
                placeholder_text_multiple: "Wählen Sie die Fächer aus",
                no_results_text: "Sie haben noch kein Fach erstellt"
            });
        });
    </script>
}

NOTEit/NOTEit/Views/Semester/Delete.cshtml
@model NOTEit.Models.Semester

@{
    ViewBag.Title = "Löschen";
}

<h2>@ViewBag.Title</h2>

<h3>Wollen Sie dieses Semester wirklich löschen?</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Löschen" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Zurück zur Übersicht", "Index")
</div>

NOTEit/NOTEit/Views/Semester/Details.cshtml
@model NOTEit.Models.Semester

@{
    ViewBag.Title = "Details";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Semester</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Bearbeiten", "Edit", "Semester", new { id = Model.Id }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Zurück zur Übersicht", "Index")
</div>

NOTEit/NOTEit/Views/Semester/Edit.cshtml
@model NOTEit.ViewModels.Semester.SemesterFormViewModel

@{
    ViewBag.Title = "Bearbeiten";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Semester</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(x => x.Id)
        @Html.Partial("_Form")

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Speichern" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Zurück zur Übersicht", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {
            $("#Subjects").chosen({
                placeholder_text_multiple: "Wählen Sie die Fächer aus",
                no_results_text: "Sie haben noch kein Fach erstellt"
            });
        });
    </script>
}

NOTEit/NOTEit/Views/Semester/Index.cshtml
@model IEnumerable<NOTEit.Models.Semester>

@{
    ViewBag.Title = "Semesterliste";
}

<h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Neues Semester erstellen", "Create")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Subjects)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @foreach (var subject in item.Subjects)
                {
                    @Html.ActionLink(subject.Name, "Edit", "Subject", new { id = subject.Id }, null)
                    if (subject != item.Subjects.Last())
                    {
                        @Html.DisplayName(", ")
                    }
                }
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Bearbeiten", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Löschen", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

NOTEit/NOTEit/Views/Semester/_Form.cshtml
@model NOTEit.ViewModels.Semester.SemesterFormViewModel

<div class="form-group">
    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Subjects, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.ListBoxFor(model => model.Subjects, new MultiSelectList(Model.AllSubjects, "Id", "Name"), new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Subjects, "", new { @class = "text-danger" })
    </div>
</div>